//! `openproxy sync <9router|omniroute>` — pull provider/model catalogs
//! from upstream open-source AI routers into the local `db.json`.
//!
//! The actual upstream JS/TS modules are normalised into JSON snapshots by
//! `scripts/sync/normalize-sources.mjs` (maintainer-only) and committed to
//! `src/core/model/sources/`. Those snapshots are embedded into the release
//! binary so the CLI works offline. Pass `--source-file <path>` to override
//! the embedded snapshot (useful for testing and for users who want to
//! point at a freshly-regenerated file).
//!
//! Synced models land in `db.AppDb.custom_models` and are tagged via the
//! `source`/`sourceRef`/`syncedAt` fields. `provider models list <alias>`
//! and `/v1/models` already surface custom models, so synced entries show
//! up everywhere built-ins do. `--prune` removes only entries whose
//! `source` field matches the current sync.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use clap::{Args, Subcommand};
use serde::Deserialize;
use serde_json::{json, Value};

use crate::cli::output::{emit_error, emit_robot, humanln, OutputCtx};
use crate::core::model::catalog::provider_catalog;
use crate::db::Db;
use crate::types::{AppDb, CustomModel};

/// Embedded snapshot of the 9router catalog. Regenerated by
/// `scripts/sync/normalize-sources.mjs`.
pub(crate) const EMBEDDED_9ROUTER_JSON: &str = include_str!("../core/model/sources/9router.json");

/// Embedded snapshot of the OmniRoute catalog. Regenerated by
/// `scripts/sync/normalize-sources.mjs`.
pub(crate) const EMBEDDED_OMNIROUTE_JSON: &str =
    include_str!("../core/model/sources/omniroute.json");

#[derive(Debug, Clone, Subcommand)]
pub enum SyncCmd {
    /// Sync provider catalog from decolua/9router.
    ///
    /// Aliases: `9router`.
    #[command(alias = "9router")]
    NineRouter(SyncOpts),
    /// Sync provider catalog from diegosouzapw/OmniRoute.
    Omniroute(SyncOpts),
}

#[derive(Debug, Clone, Args)]
pub struct SyncOpts {
    /// Show the diff but do not mutate `db.json`.
    #[arg(long)]
    pub dry_run: bool,

    /// Remove customModels tagged with this source that are no longer in
    /// the upstream catalog. Built-in models and customModels tagged with
    /// a different (or no) source are never touched.
    #[arg(long)]
    pub prune: bool,

    /// Load the snapshot from a local file instead of the embedded one.
    /// Useful for testing freshly-regenerated snapshots without rebuilding.
    #[arg(long, value_name = "PATH")]
    pub source_file: Option<PathBuf>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SyncSource {
    NineRouter,
    Omniroute,
}

impl SyncSource {
    fn name(self) -> &'static str {
        match self {
            SyncSource::NineRouter => "9router",
            SyncSource::Omniroute => "omniroute",
        }
    }

    fn embedded_json(self) -> &'static str {
        match self {
            SyncSource::NineRouter => EMBEDDED_9ROUTER_JSON,
            SyncSource::Omniroute => EMBEDDED_OMNIROUTE_JSON,
        }
    }
}

/// Snapshot file shape produced by `scripts/sync/normalize-sources.mjs`.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceSnapshot {
    pub source: String,
    #[serde(default)]
    pub r#ref: String,
    #[serde(default)]
    pub generated_at: String,
    #[serde(default)]
    pub provider_id_to_alias: BTreeMap<String, String>,
    #[serde(default)]
    pub providers: Vec<SourceProvider>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceProvider {
    pub id: String,
    pub alias: String,
    #[serde(default)]
    pub format: Option<String>,
    #[serde(default)]
    pub auth_type: Option<String>,
    #[serde(default)]
    pub base_url: Option<String>,
    #[serde(default)]
    pub models: Vec<SourceModel>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceModel {
    pub id: String,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default = "default_model_kind")]
    pub kind: String,
    #[serde(default)]
    pub context_length: Option<u64>,
    #[serde(default)]
    pub max_output_tokens: Option<u64>,
}

fn default_model_kind() -> String {
    "llm".to_string()
}

/// Translation from upstream "kind" to openproxy's CustomModel `type` field.
fn kind_to_type(kind: &str) -> &'static str {
    match kind {
        "llm" => "llm",
        "chat" => "chat",
        "embedding" => "embedding",
        "image" => "image",
        "tts" => "tts",
        "stt" => "stt",
        "audio" => "audio",
        "search" | "websearch" => "search",
        "fetch" | "webfetch" => "fetch",
        "video" => "video",
        _ => "chat",
    }
}

/// Aggregated diff returned by `compute_diff`, also serialised verbatim
/// into the robot envelope.
#[derive(Debug, Default, Clone, serde::Serialize)]
pub struct SyncDiff {
    pub created: Vec<ModelRef>,
    pub updated: Vec<ModelRef>,
    pub unchanged: Vec<ModelRef>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub deleted: Vec<ModelRef>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub stale: Vec<ModelRef>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ModelRef {
    pub provider_alias: String,
    pub model_id: String,
}

impl SyncDiff {
    pub fn summary(&self) -> String {
        let mut parts = Vec::new();
        if !self.created.is_empty() {
            parts.push(format!("{} created", self.created.len()));
        }
        if !self.updated.is_empty() {
            parts.push(format!("{} updated", self.updated.len()));
        }
        if !self.unchanged.is_empty() {
            parts.push(format!("{} unchanged", self.unchanged.len()));
        }
        if !self.deleted.is_empty() {
            parts.push(format!("{} deleted", self.deleted.len()));
        }
        if !self.stale.is_empty() {
            parts.push(format!(
                "{} stale (use --prune to remove)",
                self.stale.len()
            ));
        }
        if parts.is_empty() {
            "nothing to do".into()
        } else {
            parts.join(", ")
        }
    }
}

pub(crate) fn load_snapshot(
    source: SyncSource,
    override_path: Option<&PathBuf>,
) -> anyhow::Result<SourceSnapshot> {
    let raw = match override_path {
        Some(path) => std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("failed to read {}: {e}", path.display()))?,
        None => source.embedded_json().to_string(),
    };
    let snapshot: SourceSnapshot =
        serde_json::from_str(&raw).map_err(|e| anyhow::anyhow!("failed to parse snapshot: {e}"))?;
    if !snapshot.source.is_empty() && snapshot.source != source.name() {
        anyhow::bail!(
            "snapshot source mismatch: file says {:?}, expected {:?}",
            snapshot.source,
            source.name()
        );
    }
    Ok(snapshot)
}

/// Plan a sync without mutating anything. The plan is the source of truth
/// for both the dry-run envelope and the actual mutation.
#[derive(Debug, Default)]
struct SyncPlan {
    new_models: Vec<CustomModel>,
    updated_models: Vec<UpdatedModel>,
    delete_pairs: Vec<(String, String)>, // (provider_alias, model_id)
    diff: SyncDiff,
}

#[derive(Debug)]
struct UpdatedModel {
    provider_alias: String,
    id: String,
    new_name: Option<String>,
    new_extra: BTreeMap<String, Value>,
}

pub(crate) fn compute_plan(
    snap: &AppDb,
    snapshot: &SourceSnapshot,
    source: SyncSource,
    now_iso: &str,
    prune: bool,
) -> SyncPlan {
    let catalog = provider_catalog();
    let source_tag = source.name();

    // Existing customModels indexed by (alias, id), restricted to entries
    // tagged with the current source so we know what we previously synced.
    let mut existing_synced: BTreeMap<(String, String), &CustomModel> = BTreeMap::new();
    for m in &snap.custom_models {
        if model_source(m).as_deref() == Some(source_tag) {
            existing_synced.insert((m.provider_alias.clone(), m.id.clone()), m);
        }
    }

    // All existing model ids for each alias, regardless of source — so we
    // do not duplicate a model that already exists (built-in or otherwise).
    let mut existing_ids: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for m in &snap.custom_models {
        existing_ids
            .entry(m.provider_alias.clone())
            .or_default()
            .insert(m.id.clone());
    }
    for entry in catalog.iter_provider_models() {
        let set = existing_ids.entry(entry.alias.clone()).or_default();
        for model in &entry.models {
            set.insert(model.id.clone());
        }
    }

    let mut plan = SyncPlan::default();
    let mut upstream_keys: BTreeSet<(String, String)> = BTreeSet::new();

    for provider in &snapshot.providers {
        let alias = provider.alias.clone();
        for model in &provider.models {
            upstream_keys.insert((alias.clone(), model.id.clone()));
            let model_ref = ModelRef {
                provider_alias: alias.clone(),
                model_id: model.id.clone(),
            };

            if let Some(existing) = existing_synced.get(&(alias.clone(), model.id.clone())) {
                // Was previously synced — check whether name/extra changed.
                let new_extra = build_extra(provider, model, source_tag, &snapshot.r#ref, now_iso);
                let same_name = existing.name.as_deref() == model.name.as_deref();
                let same_extra = extra_subset_equal(&existing.extra, &new_extra);
                if same_name && same_extra {
                    plan.diff.unchanged.push(model_ref);
                } else {
                    plan.updated_models.push(UpdatedModel {
                        provider_alias: alias.clone(),
                        id: model.id.clone(),
                        new_name: model.name.clone(),
                        new_extra,
                    });
                    plan.diff.updated.push(model_ref);
                }
                continue;
            }

            // Not in our prior sync. If it exists at all (built-in or
            // user-added without source tag), treat as unchanged so we
            // don't shadow it.
            if existing_ids
                .get(&alias)
                .map(|s| s.contains(&model.id))
                .unwrap_or(false)
            {
                plan.diff.unchanged.push(model_ref);
                continue;
            }

            // Genuinely new: stage a CustomModel write.
            let extra = build_extra(provider, model, source_tag, &snapshot.r#ref, now_iso);
            plan.new_models.push(CustomModel {
                provider_alias: alias.clone(),
                id: model.id.clone(),
                r#type: kind_to_type(&model.kind).to_string(),
                name: model.name.clone(),
                extra,
            });
            plan.diff.created.push(model_ref);
        }
    }

    // Anything we previously synced that is no longer in the upstream is
    // either "stale" (default) or "delete" (if --prune).
    for key in existing_synced.keys() {
        if !upstream_keys.contains(key) {
            let model_ref = ModelRef {
                provider_alias: key.0.clone(),
                model_id: key.1.clone(),
            };
            if prune {
                plan.delete_pairs.push(key.clone());
                plan.diff.deleted.push(model_ref);
            } else {
                plan.diff.stale.push(model_ref);
            }
        }
    }

    sort_refs(&mut plan.diff.created);
    sort_refs(&mut plan.diff.updated);
    sort_refs(&mut plan.diff.unchanged);
    sort_refs(&mut plan.diff.deleted);
    sort_refs(&mut plan.diff.stale);

    plan
}

fn sort_refs(refs: &mut Vec<ModelRef>) {
    refs.sort_by(|a, b| {
        a.provider_alias
            .cmp(&b.provider_alias)
            .then_with(|| a.model_id.cmp(&b.model_id))
    });
}

fn model_source(m: &CustomModel) -> Option<String> {
    m.extra.get("source").and_then(|v| match v {
        Value::String(s) => Some(s.clone()),
        _ => None,
    })
}

fn build_extra(
    provider: &SourceProvider,
    model: &SourceModel,
    source: &str,
    source_ref: &str,
    now_iso: &str,
) -> BTreeMap<String, Value> {
    let mut extra: BTreeMap<String, Value> = BTreeMap::new();
    extra.insert("source".into(), Value::String(source.into()));
    extra.insert("sourceRef".into(), Value::String(source_ref.into()));
    extra.insert("syncedAt".into(), Value::String(now_iso.into()));
    extra.insert("kind".into(), Value::String(model.kind.clone()));
    extra.insert(
        "sourceProviderId".into(),
        Value::String(provider.id.clone()),
    );
    if let Some(ctx) = model.context_length {
        extra.insert("contextLength".into(), Value::from(ctx));
    }
    if let Some(mot) = model.max_output_tokens {
        extra.insert("maxOutputTokens".into(), Value::from(mot));
    }
    if let Some(fmt) = &provider.format {
        extra.insert("providerFormat".into(), Value::String(fmt.clone()));
    }
    if let Some(base) = &provider.base_url {
        extra.insert("providerBaseUrl".into(), Value::String(base.clone()));
    }
    if let Some(at) = &provider.auth_type {
        extra.insert("providerAuthType".into(), Value::String(at.clone()));
    }
    extra
}

/// Equality check that tolerates ordering differences and is restricted
/// to the keys we control (so unrelated extras a user added stay intact).
fn extra_subset_equal(existing: &BTreeMap<String, Value>, fresh: &BTreeMap<String, Value>) -> bool {
    // We only care that the keys we own match; ignore syncedAt because that
    // would force an update on every run.
    let ignore = ["syncedAt"];
    for (k, v) in fresh {
        if ignore.contains(&k.as_str()) {
            continue;
        }
        if existing.get(k) != Some(v) {
            return false;
        }
    }
    true
}

pub async fn run(cmd: SyncCmd, db: &Db, ctx: OutputCtx) -> anyhow::Result<()> {
    match cmd {
        SyncCmd::NineRouter(opts) => run_one(db, ctx, SyncSource::NineRouter, opts).await,
        SyncCmd::Omniroute(opts) => run_one(db, ctx, SyncSource::Omniroute, opts).await,
    }
}

async fn run_one(
    db: &Db,
    ctx: OutputCtx,
    source: SyncSource,
    opts: SyncOpts,
) -> anyhow::Result<()> {
    let snapshot = match load_snapshot(source, opts.source_file.as_ref()) {
        Ok(snap) => snap,
        Err(e) => {
            let _ = emit_error(ctx, "sync.load_snapshot", &e.to_string());
            return Err(e);
        }
    };
    let now_iso = chrono_like_now();
    let snap = db.snapshot();
    let plan = compute_plan(&snap, &snapshot, source, &now_iso, opts.prune);

    if !opts.dry_run
        && (!plan.new_models.is_empty()
            || !plan.updated_models.is_empty()
            || !plan.delete_pairs.is_empty())
    {
        let to_create = plan.new_models.clone();
        let updates = plan
            .updated_models
            .iter()
            .map(|u| {
                (
                    u.provider_alias.clone(),
                    u.id.clone(),
                    u.new_name.clone(),
                    u.new_extra.clone(),
                )
            })
            .collect::<Vec<_>>();
        let to_delete = plan.delete_pairs.clone();
        db.update(move |app| {
            // Apply updates first (so we don't accidentally trip over them
            // during create).
            for (alias, id, new_name, new_extra) in &updates {
                if let Some(existing) = app
                    .custom_models
                    .iter_mut()
                    .find(|m| &m.provider_alias == alias && &m.id == id)
                {
                    existing.name = new_name.clone();
                    // Preserve any extra keys we don't own.
                    let preserve = preserved_keys();
                    let mut merged = existing.extra.clone();
                    for k in new_extra.keys() {
                        merged.remove(k);
                    }
                    // Drop our owned keys before re-applying so removed
                    // keys actually disappear.
                    let owned = owned_extra_keys();
                    merged.retain(|k, _| {
                        !owned.contains(&k.as_str()) || preserve.contains(&k.as_str())
                    });
                    for (k, v) in new_extra {
                        merged.insert(k.clone(), v.clone());
                    }
                    existing.extra = merged;
                }
            }
            // Delete stale entries.
            if !to_delete.is_empty() {
                let set: std::collections::HashSet<(String, String)> =
                    to_delete.iter().cloned().collect();
                app.custom_models
                    .retain(|m| !set.contains(&(m.provider_alias.clone(), m.id.clone())));
            }
            // Append new models.
            for new in to_create {
                app.custom_models.push(new);
            }
        })
        .await?;
    }

    let envelope = json!({
        "source": source.name(),
        "ref": snapshot.r#ref,
        "generatedAt": snapshot.generated_at,
        "dryRun": opts.dry_run,
        "prune": opts.prune,
        "diff": plan.diff,
    });

    if ctx.is_robot() {
        emit_robot("openproxy.v1.sync.apply", envelope)?;
    } else {
        humanln(
            ctx,
            format!(
                "sync {} ({}): {}",
                source.name(),
                snapshot.r#ref,
                plan.diff.summary()
            ),
        );
        if opts.dry_run {
            humanln(ctx, "(dry-run — db.json was not modified)");
        }
        if !plan.diff.stale.is_empty() && !opts.prune {
            humanln(
                ctx,
                format!(
                    "  {} stale entr{} — rerun with --prune to remove.",
                    plan.diff.stale.len(),
                    if plan.diff.stale.len() == 1 {
                        "y"
                    } else {
                        "ies"
                    }
                ),
            );
        }
    }
    Ok(())
}

fn owned_extra_keys() -> &'static [&'static str] {
    &[
        "source",
        "sourceRef",
        "syncedAt",
        "kind",
        "sourceProviderId",
        "contextLength",
        "maxOutputTokens",
        "providerFormat",
        "providerBaseUrl",
        "providerAuthType",
    ]
}

fn preserved_keys() -> &'static [&'static str] {
    &[]
}

/// Minimal RFC3339 timestamp in UTC. We avoid pulling in `chrono` because
/// the rest of the CLI uses ad-hoc strings for `updated_at`. This helper
/// is `pub(crate)` so tests can mock-fix the timestamp.
pub(crate) fn chrono_like_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format_iso8601_utc(secs)
}

fn format_iso8601_utc(epoch_secs: u64) -> String {
    // Days from civil — adapted from Howard Hinnant.
    let z = epoch_secs / 86_400;
    let secs_of_day = epoch_secs % 86_400;
    let h = secs_of_day / 3600;
    let m = (secs_of_day % 3600) / 60;
    let s = secs_of_day % 60;

    let z_i64 = z as i64 + 719_468;
    let era = if z_i64 >= 0 {
        z_i64 / 146_097
    } else {
        (z_i64 - 146_096) / 146_097
    };
    let doe = (z_i64 - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = (yoe as i64) + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m_civ = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let y = (if m_civ <= 2 { y + 1 } else { y }) as i32;

    format!("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z", y, m_civ, d, h, m, s)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_app() -> AppDb {
        AppDb::default()
    }

    fn sample_snapshot() -> SourceSnapshot {
        SourceSnapshot {
            source: "9router".into(),
            r#ref: "v0.4.55".into(),
            generated_at: "2026-05-19T14:00:00Z".into(),
            provider_id_to_alias: BTreeMap::new(),
            providers: vec![SourceProvider {
                id: "fake-provider".into(),
                alias: "fakeprov".into(),
                format: Some("openai".into()),
                auth_type: Some("apikey".into()),
                base_url: Some("https://example.com/v1/chat/completions".into()),
                models: vec![SourceModel {
                    id: "fakeprov/unique-model-id".into(),
                    name: Some("Sample".into()),
                    kind: "llm".into(),
                    context_length: Some(1_047_576),
                    max_output_tokens: None,
                }],
            }],
        }
    }

    #[test]
    fn diff_on_empty_db_creates_everything() {
        let app = empty_app();
        let snap = sample_snapshot();
        let plan = compute_plan(&app, &snap, SyncSource::NineRouter, "now", false);
        assert_eq!(plan.diff.created.len(), 1);
        assert_eq!(plan.diff.unchanged.len(), 0);
        assert_eq!(plan.diff.updated.len(), 0);
        assert_eq!(plan.new_models.len(), 1);
        let m = &plan.new_models[0];
        assert_eq!(m.provider_alias, "fakeprov");
        assert_eq!(m.id, "fakeprov/unique-model-id");
        assert_eq!(m.r#type, "llm");
        assert_eq!(m.extra.get("source").unwrap().as_str(), Some("9router"));
        assert_eq!(m.extra.get("sourceRef").unwrap().as_str(), Some("v0.4.55"));
        assert_eq!(
            m.extra.get("contextLength").unwrap().as_u64(),
            Some(1_047_576)
        );
    }

    #[test]
    fn diff_with_existing_synced_marks_unchanged() {
        let mut app = empty_app();
        let snap = sample_snapshot();
        // Pre-populate db.custom_models with the same model, tagged.
        let mut model = CustomModel {
            provider_alias: "fakeprov".into(),
            id: "fakeprov/unique-model-id".into(),
            r#type: "chat".into(),
            name: Some("Sample".into()),
            extra: BTreeMap::new(),
        };
        model
            .extra
            .insert("source".into(), Value::String("9router".into()));
        model
            .extra
            .insert("sourceRef".into(), Value::String("v0.4.55".into()));
        model
            .extra
            .insert("syncedAt".into(), Value::String("earlier".into()));
        model
            .extra
            .insert("kind".into(), Value::String("llm".into()));
        model.extra.insert(
            "sourceProviderId".into(),
            Value::String("fake-provider".into()),
        );
        model
            .extra
            .insert("contextLength".into(), Value::from(1_047_576u64));
        model
            .extra
            .insert("providerFormat".into(), Value::String("openai".into()));
        model.extra.insert(
            "providerBaseUrl".into(),
            Value::String("https://example.com/v1/chat/completions".into()),
        );
        model
            .extra
            .insert("providerAuthType".into(), Value::String("apikey".into()));
        app.custom_models.push(model);

        let plan = compute_plan(&app, &snap, SyncSource::NineRouter, "now", false);
        assert_eq!(plan.diff.unchanged.len(), 1);
        assert_eq!(plan.diff.created.len(), 0);
        assert_eq!(plan.diff.updated.len(), 0);
    }

    #[test]
    fn stale_appears_without_prune_and_deletes_with_prune() {
        let mut app = empty_app();
        let snap = sample_snapshot();
        let mut model = CustomModel {
            provider_alias: "fakeprov".into(),
            id: "fakeprov/legacy-id".into(),
            r#type: "chat".into(),
            name: None,
            extra: BTreeMap::new(),
        };
        model
            .extra
            .insert("source".into(), Value::String("9router".into()));
        app.custom_models.push(model);

        let plan_no_prune = compute_plan(&app, &snap, SyncSource::NineRouter, "now", false);
        assert_eq!(plan_no_prune.diff.stale.len(), 1);
        assert_eq!(plan_no_prune.diff.deleted.len(), 0);
        assert!(plan_no_prune.delete_pairs.is_empty());

        let plan_prune = compute_plan(&app, &snap, SyncSource::NineRouter, "now", true);
        assert_eq!(plan_prune.diff.deleted.len(), 1);
        assert_eq!(plan_prune.diff.stale.len(), 0);
        assert_eq!(
            plan_prune.delete_pairs,
            vec![("fakeprov".to_string(), "fakeprov/legacy-id".to_string())]
        );
    }

    #[test]
    fn untagged_existing_models_are_left_alone() {
        let mut app = empty_app();
        let snap = sample_snapshot();
        // A user-added model with the same id but no source tag.
        let model = CustomModel {
            provider_alias: "fakeprov".into(),
            id: "fakeprov/unique-model-id".into(),
            r#type: "chat".into(),
            name: Some("My copy".into()),
            extra: BTreeMap::new(),
        };
        app.custom_models.push(model);

        let plan = compute_plan(&app, &snap, SyncSource::NineRouter, "now", true);
        assert_eq!(
            plan.diff.created.len(),
            0,
            "should not duplicate the user's entry"
        );
        assert_eq!(plan.diff.unchanged.len(), 1);
        assert!(
            plan.delete_pairs.is_empty(),
            "prune must not touch untagged entries"
        );
    }

    #[test]
    fn iso8601_formatter_known_values() {
        assert_eq!(format_iso8601_utc(0), "1970-01-01T00:00:00Z");
        assert_eq!(format_iso8601_utc(1_700_000_000), "2023-11-14T22:13:20Z");
    }

    #[test]
    fn embedded_snapshots_parse() {
        let nine: SourceSnapshot = serde_json::from_str(EMBEDDED_9ROUTER_JSON).unwrap();
        assert_eq!(nine.source, "9router");
        assert!(nine.providers.iter().any(|p| p.alias == "cc"));
        let omni: SourceSnapshot = serde_json::from_str(EMBEDDED_OMNIROUTE_JSON).unwrap();
        assert_eq!(omni.source, "omniroute");
        assert!(omni.providers.iter().any(|p| p.id == "github-models"));
        assert!(omni.providers.iter().any(|p| p.id == "hackclub"));
    }
}
